name: Deploy to github page
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout theme
      uses: actions/checkout@v2
      with:
        persist-credentials: false
        path: ./candelas
    - name: Clone hexo-theme-unit-test
      run: |
        git clone https://github.com/hexojs/hexo-theme-unit-test.git
        cd ./hexo-theme-unit-test
        mkdir themes
        npm install
    - name: Init Github pages
      run: |
        mv ./candelas/.git $GITHUB_WORKSPACE
        mv ./candelas ./hexo-theme-unit-test/themes
        cd ./hexo-theme-unit-test
        npx hexo clean
        npx hexo config theme candelas
        npx hexo new page categories
        cp ./themes/candelas/.github/resources/categories.md ./source/categories/index.md
        npx hexo generate
        mv ./public $GITHUB_WORKSPACE
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: gh-pages
        FOLDER: public
